name: deploy-docs

# Only run this when the master branch changes
on:
  push:
    branches:
      - main
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Copy readme
        run: |
          cp README.md ./docs/index.md
      - name: Deploy docs
        run: |
          poetry run mkdocs gh-deploy --force
